### ISSUE TITLE
Installation like to sketch library is broken

### ISSUE THREAD

**Issue by Hippogriff** [antonymarion/inverseCSG#8]
Since the link provided for sketch library didn't work, I ended up installing https://people.csail.mit.edu/asolar/sketch-1.7.6.tar.gz

Rest of the installation worked fine. However, when I run the code on simplest cube example, the code runs for over 10 minutes and give the following error:

`

    Using 6 bits to encode the constraints.
    bash /home/hippogriff/Downloads/sketch-1.7.6 -V 10 --fe-inc /home/hippogriff/Downloads/sketch-1.7.6/sketch-frontend/src/sketchlib/ --fe-kill-asserts --fe-output-test --fe-output-dir /home/hippogriff/cape_coalwood/one_cube/sketch_output/ --fe-cegis-path /home/hippogriff/Downloads/sketch-1.7.6/sketch-backend/src/SketchSolver/cegis /home/hippogriff/cape_coalwood/one_cube/sketches/one_cube_954_0.sk --fe-timeout 10.000000
    Problem is too hard. Need segmentation.
    Traceback (most recent call last):
    File "main.py", line 47, in <module>
        sketch_pipeline.RunSketchPipeline()
    File "/home/hippogriff/cape_coalwood/inverseCSG/sketch_pipeline.py", line 718, in RunSketchPipeline
        part_file[:-len('.data')])
    File "/home/hippogriff/cape_coalwood/inverseCSG/point_cloud_seg.py", line 27, in SegmentPointCloud
        cluster_result.fit(points)
    File "/home/hippogriff/softwares/anaconda3/envs/conv_onet/lib/python3.6/site-packages/sklearn/cluster/_agglomerative.py", line 819, in fit
        X = self._validate_data(X, ensure_min_samples=2, estimator=self)
    File "/home/hippogriff/softwares/anaconda3/envs/conv_onet/lib/python3.6/site-packages/sklearn/base.py", line 420, in _validate_data
        X = check_array(X, **check_params)
    File "/home/hippogriff/softwares/anaconda3/envs/conv_onet/lib/python3.6/site-packages/sklearn/utils/validation.py", line 72, in inner_f
        return f(**kwargs)
    File "/home/hippogriff/softwares/anaconda3/envs/conv_onet/lib/python3.6/site-packages/sklearn/utils/validation.py", line 653, in check_array
        context))
    ValueError: Found array with 1 sample(s) (shape=(1, 3)) while a minimum of 2 is required by AgglomerativeClustering.

`

**Comment by antonymarion** [comment]
Hi,

I suggest that you use the same version as in the CI environment which is sketch-1.7.5.

It seems like the bitbucket repo has disappeared, but you can still get the repo using the wayback machine here:
https://web.archive.org/web/20200622004002/https://bitbucket.org/gatoatigrado/sketch-backend/get/a010e0200793.zip

And to make it work, if you get any error, then you can copy paste every command from the CI https://travis-ci.com/github/antonymarion/inverseCSG/builds/147114488 within a travis docker container locally (cf https://medium.com/google-developers/how-to-run-travisci-locally-on-docker-822fc6b2db2e)
